# Generated by Django 5.2.8 on 2025-11-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
