# Generated by Django 5.2.8 on 2025-11-19 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('shop', '0008_gmailtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.variation'),
        ),
    ]
