# Generated by Django 5.2.8 on 2025-11-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderedproduct_variation'),
        ('shop', '0008_gmailtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='variations',
            field=models.ManyToManyField(blank=True, related_name='ordered_products', to='shop.variation'),
        ),
    ]
