# Generated by Django 5.2.8 on 2025-11-19 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderedproduct_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='variation',
        ),
    ]
