# Generated by Django 5.2.8 on 2025-11-20 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderedproduct_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='size',
        ),
    ]
